-- drop table

DROP TABLE JUGADOR_PARTICIPA;
DROP TABLE PREMIO;
DROP TABLE TORNEO;
DROP TABLE JUGADOR;

-- create table

CREATE TABLE JUGADOR(
	DNI_JUGADOR VARCHAR(9),
	NOMBRE_JUGADOR VARCHAR(30) NOT NULL,
	APELLIDO1 VARCHAR(30) NOT NULL,
	APELLIDO2 VARCHAR(30),
	ALIAS VARCHAR(30) NOT NULL,
	F_NAC DATE,
	CONSTRAINT U_ALIAS UNIQUE (ALIAS),
	CONSTRAINT PK_JUGADOR PRIMARY KEY(DNI_JUGADOR)
	);

CREATE TABLE TORNEO(
	COD_TORNEO VARCHAR(9),
	NOMBRE_TORNEO VARCHAR(50) NOT NULL,
	F_INICIO DATE NOT NULL,
	F_FIN DATE NOT NULL,
	ENTRADA NUMBER(6,2),
	TIPO_TORNEO CHAR(9),
	CONSTRAINT U_NOMBRE UNIQUE (NOMBRE_TORNEO),
	CONSTRAINT CHECK_FECHAS CHECK (F_FIN >= F_INICIO),
	CONSTRAINT CHECK_TIPO CHECK(TIPO_TORNEO IN ('FREEZEOUT', 'FREEROLLS')),
	CONSTRAINT PK_TORNEO PRIMARY KEY(COD_TORNEO)
);

CREATE TABLE PREMIO(
	NUM_PREMIO NUMBER(3),
	POSICION NUMBER(3) NOT NULL,
	CANTIDAD NUMBER(12) NOT NULL,
	COD_TORNEO VARCHAR(9),
	CONSTRAINT CHECK_NUM CHECK (NUM_PREMIO >= 1),
	CONSTRAINT CHECK_POS CHECK (POSICION >= 1),
	CONSTRAINT CHECK_CANTIDAD CHECK (CANTIDAD >= 0),
	CONSTRAINT FK_PREMIO FOREIGN KEY (COD_TORNEO) REFERENCES TORNEO(COD_TORNEO) ON DELETE CASCADE,
	CONSTRAINT PK_PREMIO PRIMARY KEY (COD_TORNEO, NUM_PREMIO)
);

CREATE TABLE JUGADOR_PARTICIPA(
	DNI_JUGADOR VARCHAR(9),
	COD_TORNEO VARCHAR(9),
	POSICION_FINAL NUMBER(3),
	CONSTRAINT CHECK_POSF CHECK (POSICION_FINAL >= 1),
	CONSTRAINT FK_JUGP1 FOREIGN KEY (DNI_JUGADOR) REFERENCES JUGADOR(DNI_JUGADOR) ON DELETE CASCADE,
	CONSTRAINT FK_JUGP2 FOREIGN KEY (COD_TORNEO) REFERENCES TORNEO(COD_TORNEO) ON DELETE CASCADE,
	CONSTRAINT PK_JUGP PRIMARY KEY (DNI_JUGADOR, COD_TORNEO)
);

